# Generated by Django 3.0.5 on 2020-04-05 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=400)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200, null=True)),
                ('answer3', models.CharField(max_length=200, null=True)),
                ('times_solved', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(max_length=100)),
                ('team_member2', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member3', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member4', models.CharField(blank=True, max_length=100, null=True)),
                ('team_member5', models.CharField(blank=True, max_length=100, null=True)),
                ('last_wrong_answered_made_on', models.DateTimeField(blank=True, null=True, verbose_name='last wrong answer date')),
                ('last_question_answered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hunt.Question')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
