# Generated by Django 3.0.5 on 2020-04-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='team',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_member2',
            field=models.CharField(blank=True, default='Chuck', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_member3',
            field=models.CharField(blank=True, default='Carly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='team_member4',
            field=models.CharField(blank=True, default='Jackson', max_length=100, null=True),
        ),
    ]
