# Generated by Django 3.0.5 on 2020-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_auto_20200406_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['number']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_question_answered',
        ),
        migrations.AddField(
            model_name='profile',
            name='questions_answered',
            field=models.ManyToManyField(blank=True, null=True, to='hunt.Question'),
        ),
    ]
