# Generated by Django 3.0.5 on 2020-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_auto_20200406_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
