# Generated by Django 3.0.5 on 2020-04-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_auto_20200406_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_wrong_answered_made_on',
            new_name='last_wrong_answer_made_on',
        ),
    ]
