# Generated by Django 3.0.5 on 2020-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_auto_20200409_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='text',
        ),
    ]
